### ISSUE TITLE
broken after update

### ISSUE THREAD

**Issue by GustavoPrietoP** [chadcat7/prism#2]
Hey, I'm getting this error after updating to the latest version, happens after I try to switch colorschemes: 
![image](https://github.com/chadcat7/prism/assets/70907734/799db02c-d050-442b-b783-009e580d2fbb)

**Comment by namishh** [comment]
solved in the latest commit, just for refreshing, delete all the prism related folders in .local/share/nvim first

**Comment by GustavoPrietoP** [comment]
thank you for the quick fix.
