### ISSUE TITLE
:PrismTelescope currently not working

### ISSUE THREAD

**Issue by vivifalls** [chadcat7/prism#3]
As title says, `:PrismTelescope` does not work as of Neovim version 0.9.2-1, I enter the command and nothing happens.

**Comment by vivifalls** [comment]
After some more tests, none of the commands work, and the plugin is in fact installed (via Packer, but I suppose it doesn't make a difference).

**Comment by namishh** [comment]
1. is the plugin loaded `:PackerStatus`
2. just remove all the prism folders in `~/.local/share/nvim/` and run again
3. also update prism with `:PackerSync` because i have made some significant fixes

**Comment by vivifalls** [comment]
Packer does show that prism is loaded, I reinstalled it and all. There's no prism folder inside `~/.local/share/nvim/` weirdly, the commands still don't work too.

**Comment by namishh** [comment]
show me your prism config (you have a prism config right)

**Comment by vivifalls** [comment]
Turns out i didn't have a config file, i thought the configuration in the README was supposed to be the defaults the plugin came with (as it is with a lot of them). Creating a `prism.lua` file and appending the config there made the commands work.

I think a good course of action would be implicitly specifying that the configuration must be made or else the plugin won't work at all or just make it load itself as a default config. Either way, thank you for the time
